const storyL=()=>LOCALES[lang].firstDay;
const storyMoney=n=>new Intl.NumberFormat(lang,{style:'currency',currency:'BRL'}).format(n/100);
function storyCommit(action){const next=GameState.clone(state);try{if(action(next)===false)return false;FirstDay.sync(next);new QuestManager(next).sync();saves.save(activeSlot,next);state=next;missions=new QuestManager(state);ui();return true}catch(e){$('yardFeedback').textContent=LOCALES[lang].system.saveError;return false}}
// Cenas do Ato I/II entregues por Gabriel no portao, na ordem em que os fatos acontecem (flag do evento -> cena).
const STORY_SCENES=[['circuit','E006'],['observe','E008'],['hen','E009'],['cross','E010'],['egg','E011'],['birth','E012'],['janilson','E013'],['nasceu','E015'],['niva','E016'],['titulo','E017'],['claudineia','E018'],['viagem','E019'],['bruno','E020'],['top10','E021'],['linhagem','E022'],['nacional','E023'],['campeao_nacional','E024'],['internacional','E025'],['convite_mundial','E026'],['mundial','E027'],['epilogo','E028']];
function storyPendingScene(){const d=FirstDay.data(state);if(d.phase!=='complete')return null;const sc=storyL().scenes;for(const [id,flag] of STORY_SCENES)if(EventFlags.has(state,flag)&&sc[id]&&(d.dialogue[id]||0)<sc[id].length)return id;return null}
// Quem esta no portao: Gabriel, ou o visitante da cena pendente (Marivaldo/Janilson).
function storyNpcAtGate(){const id=FirstDay.enabled(state)?storyPendingScene():null;return ['observe','hen','cross'].includes(id)?'marivaldo':id==='janilson'?'janilson':id==='claudineia'?'claudineia':id==='niva'?'niva':'gabriel'}
function storyObjective(){const d=FirstDay.data(state),l=storyL();if(!d.intro)return l.talk;if(d.phase==='routine')return l[['prepare','plant','water','collect'].find(t=>!EventFlags.has(state,'day1_'+t))]||l.talk;if(d.phase==='outbound'||d.phase==='work')return l.goWork;if(d.phase==='return')return l.returnHome;if(d.phase==='bought')return l.sleep;if(d.phase==='care')return d.reaction?l.careHint:l.reaction;
 if(d.phase==='complete'){const f=k=>EventFlags.has(state,k),pending=storyPendingScene();if(pending==='observe')return l.observeTalk;if(pending==='circuit')return l.circuitTalk;if(pending)return l.sceneTalk;if(f('linhagem_visto')&&!f('linhagem_nomeada'))return l.lineageName;if(f('nacional_visto')&&!f('nacional_campeao'))return l.nationalGo;if(f('internacional_visto')&&!f('intl_dest_4'))return l.intlGo;if(f('convite_mundial_visto')&&!f('mundial_campeao'))return l.worldGo;if(f('epilogo_visto'))return l.postgame;if(f('niva_visto')&&!f('niva_contratado'))return l.nivaHireTalk;if(f('viagem_visto')&&!f('regional_disputado'))return l.regionalFight;if(d.circuitOpen&&!f('E007'))return l.circuitFight}return l.done}
function storyName(id){return FirstDay.enabled(state)&&['friend','sign'].includes(id)?storyL()[id]:LOCALES[lang].names[id]}
function storyInteractionName(id){const l=storyL();if(id.startsWith('workShelf'))return l.pickAt+' · '+l.items[Number(id.slice(-1))];if(id.startsWith('workBench'))return l.deliverAt+' · '+l['bench'+(id.endsWith('0')?'A':'B')];return storyName(id)}
// Vinheta da viagem de van (Ato IV): ~14 s, pulavel, com 1 evento variavel (pneu, GPS ou vaca) escolhido pelo dia.
let tripStart=0,tripRaf=0;
// P016: sprites pintados no padrao do jogo para a van e a vaca da vinheta (substituem os retangulos vetoriais).
const tripSprites={van:new Image(),cow:new Image()};tripSprites.van.src='assets/trip/van.png';tripSprites.cow.src='assets/trip/cow.png';
function drawTrip(cv,t,ev){const c=cv.getContext('2d'),W=cv.width,H=cv.height;c.clearRect(0,0,W,H);
 const sky=c.createLinearGradient(0,0,0,H*.6);sky.addColorStop(0,'#7fb2d6');sky.addColorStop(1,'#e8d9a6');c.fillStyle=sky;c.fillRect(0,0,W,H*.62);
 const scroll=(t*70)%W;c.fillStyle='#5f7a3e';for(let i=-1;i<4;i++){const x=i*260-scroll*.3%260;c.beginPath();c.ellipse(x+130,H*.62,170,46,0,Math.PI,0);c.fill()}
 c.fillStyle='#6b5a3a';c.fillRect(0,H*.62,W,H*.38);c.fillStyle='#4a4038';c.fillRect(0,H*.7,W,H*.2);
 c.fillStyle='#e8d98a';for(let x=-((t*140)%80);x<W;x+=80)c.fillRect(x,H*.795,42,4);
 const stopped=ev===0&&t>5&&t<10,cowStop=ev===2&&t>6&&t<9.5,vx=W*.28+(stopped||cowStop?0:Math.sin(t*3)*2),vy=H*.7-4+(stopped||cowStop?0:Math.sin(t*9)*1.4);
 c.fillStyle='#00000030';c.beginPath();c.ellipse(vx+70,vy+56,80,7,0,0,Math.PI*2);c.fill();
 const van=tripSprites.van;
 if(van.naturalWidth){const vw=170,vh=vw*van.naturalHeight/van.naturalWidth;c.drawImage(van,vx-15,vy+30-vh,vw,vh)}
 else{c.fillStyle='#e9e6dc';c.fillRect(vx,vy-8,140,58);c.fillStyle='#c9c4b4';c.fillRect(vx,vy+30,140,8);c.fillStyle='#8fb8d0';c.fillRect(vx+86,vy,44,24);c.fillRect(vx+14,vy,60,24);c.fillStyle='#222';c.fillRect(vx+76,vy,4,24);c.fillStyle='#b5442f';c.fillRect(vx,vy+22,140,5);for(const wx of [26,106]){c.fillStyle='#222';c.beginPath();c.arc(vx+wx,vy+52,13,0,Math.PI*2);c.fill();c.fillStyle='#777';c.beginPath();c.arc(vx+wx,vy+52,5,0,Math.PI*2);c.fill()}c.fillStyle='#cb9873';for(const hx of [26,50,102])c.fillRect(vx+hx,vy+6,14,14);c.fillStyle='#282824';for(const hx of [26,50,102])c.fillRect(vx+hx,vy+4,14,5)}
 if(ev===0&&t>5&&t<10){c.fillStyle='#e05a3a';c.font='bold 22px sans-serif';c.fillText('!',vx+20,vy-14)}
 if(ev===1&&t>5&&t<10){c.fillStyle='#fff';c.fillRect(W*.62,H*.36,70,34);c.fillStyle='#2f5f9e';c.font='bold 20px sans-serif';c.fillText(Math.floor(t*3)%2?'>>':'<<',W*.62+18,H*.36+25);c.fillStyle='#6e6a62';c.fillRect(W*.62+33,H*.36+34,4,H*.26)}
 if(ev===2){const cx=W-((t-3)*90);if(cx<W+60&&cx>W*.45){const cow=tripSprites.cow;if(cow.naturalWidth){const cw=76,ch=cw*cow.naturalHeight/cow.naturalWidth;c.drawImage(cow,cx-12,H*.66+24-ch,cw,ch)}else{c.fillStyle='#f2f2f2';c.fillRect(cx,H*.66,52,24);c.fillStyle='#222';c.fillRect(cx+8,H*.66+5,10,8);c.fillRect(cx+30,H*.66+9,10,8);c.fillStyle='#f2f2f2';c.fillRect(cx-14,H*.66-6,18,14);c.fillRect(cx+6,H*.66+24,6,14);c.fillRect(cx+40,H*.66+24,6,14)}}}
}
function tripEvent(){return (state.clock.day+(EventFlags.has(state,'regional_disputado')?1:0))%3}
function renderTrip(body){const l=storyL();$('closeYard').textContent=l.close;body.className='first-day-body';$('yardTitle').textContent=l.tripTitle;
 const ev=tripEvent(),cv=document.createElement('canvas');cv.width=640;cv.height=260;cv.className='trip-canvas';cv.style.cssText='width:100%;max-width:640px;image-rendering:pixelated;border:2px solid #0006';body.append(cv);
 const cap=storyParagraph(body,l.tripGo,'story-line');
 const done=()=>{cancelAnimationFrame(tripRaf);if(storyCommit(s=>EventFlags.set(s,'viagem_anim')))openYard('scene-viagem')};
 storyButton(body,l.tripSkip,'skip',done);
 tripStart=performance.now();
 const loop=now=>{if(!$('yardPanel').open||yardView!=='trip'){cancelAnimationFrame(tripRaf);return}const t=(now-tripStart)/1000;drawTrip(cv,t,ev);
  cap.textContent=t>5&&t<10?l['tripEvent'+ev]:t>=10?l.tripArrive:l.tripGo;if(t>=14){done();return}tripRaf=requestAnimationFrame(loop)};
 tripRaf=requestAnimationFrame(loop);return true}
function storyOpenScene(id){if(id==='viagem'&&!EventFlags.has(state,'viagem_anim')){openYard('trip');return}if(id==='seller')storyCommit(s=>EventFlags.set(s,'sellerCalled'));if(id==='intro')storyCommit(s=>{EventFlags.set(s,'talkedToFriend');s.npcs.friend.met=true});openYard('scene-'+id)}
function storyInteract(id){if(id.startsWith('npc_')&&typeof favorOpen==='function')return favorOpen(id.slice(4));if(!FirstDay.enabled(state))return false;const d=FirstDay.data(state);
 if(id==='friend'){if(!d.intro)storyOpenScene('intro');else if(d.phase==='care'&&!d.reaction)storyOpenScene('reaction');else if(storyPendingScene())storyOpenScene(storyPendingScene());else if(d.phase==='complete'&&EventFlags.has(state,'niva_visto')&&!EventFlags.has(state,'niva_contratado'))openYard('niva-hire');else openYard('story-note');return true}
 if(id==='sign'){if(!EventFlags.has(state,'E001')){openYard('gate-locked');return true}return false}
 if(id==='depotDoor'){enterRoom('depot');return true}
 if(id==='depotExit'){enterRoom('yard');return true}
 if(id==='tainan'){const paidToday=d.shift?.paid&&d.shift.paidDay===state.clock.day;if(paidToday)openYard('pay');else if(d.dialogue.work>=storyL().scenes.work.length){if(storyCommit(s=>FirstDay.startWork(s))){closeYard();canvas.focus();storyWorkHUD()}}else storyOpenScene('work');return true}
 if(id.startsWith('workShelf')){storyWorkAction('pick',Number(id.slice(-1)));return true}
 if(id.startsWith('workBench')){storyWorkAction('deliver',Number(id.slice(-1)));return true}
 if(id==='encapuzado'){storyOpenScene('seller');return true}
 if(id==='firstRooster'){if(storyCommit(s=>FirstDay.care(s,'profile')))openYard('rooster');return true}return false}
function storyParagraph(body,text,cls){const p=document.createElement('p');p.textContent=text;if(cls)p.className=cls;body.append(p);return p}
function storyButton(body,text,id,action,disabled=false){const b=document.createElement('button');b.textContent=text;b.dataset.story=id;b.onclick=action;b.disabled=disabled;body.append(b);return b}
function renderStory(body){const l=storyL(),d=FirstDay.data(state);if(!d?.enabled)return false;
 const views=['shift','pay','offer','rooster','story-note','gate-locked','niva-hire','trip'];if(!views.includes(yardView)&&!yardView?.startsWith('scene-'))return false;
 $('closeYard').textContent=l.close;body.className='first-day-body';
 const heading=text=>{$('yardTitle').textContent=text};
 if(yardView.startsWith('scene-')){const id=yardView.slice(6),lines=l.scenes[id],index=d.dialogue[id]||0;if(index>=lines.length){if(id==='seller'){yardView='offer';return renderStory(body)}if(id==='work'){heading(l.workTitle);storyParagraph(body,l.workHint);storyButton(body,l.start,'start',()=>{if(storyCommit(s=>FirstDay.startWork(s))){closeYard();canvas.focus();storyWorkHUD()}});return true}heading(l.dayLabel);storyParagraph(body,id==='reaction'?l.careHint:storyObjective());return true}
 const speaker=lines[index][0],who=speaker.includes('Tainan')?'tainan':speaker.includes('Encapuzado')||speaker.includes('Hooded')?'encapuzado':speaker==='Você'||speaker==='You'?'player':speaker.includes('Gabriel')?'gabriel':speaker.includes('Marivaldo')?'marivaldo':speaker.includes('Janilson')?'janilson':speaker.includes('Niva')?'niva':speaker.includes('Renato')?'renato':speaker.includes('Bruno')?'bruno':speaker.includes('Fred')?'fred':speaker.includes('Claudineia')?'claudineia':speaker.includes('Carlos')?'principe':'seller';heading(speaker);const portrait=document.createElement('canvas');portrait.width=192;portrait.height=192;portrait.className='story-portrait';portrait.setAttribute('aria-hidden','true');const pc=portrait.getContext('2d');if(RouteArt.hasAnim(who))RouteArt.portrait(pc,who,who==='claudineia'&&index===5?1:0,192);else{pc.scale(3,3);RouteArt.person(pc,32,58,who)}body.append(portrait);storyParagraph(body,lines[index][1],'story-line');storyParagraph(body,(index+1)+' / '+lines.length,'story-page');storyButton(body,l.next,'next',()=>{if(storyCommit(s=>{const f=FirstDay.data(s);f.dialogue[id]=Math.min(lines.length,(f.dialogue[id]||0)+1);if(f.dialogue[id]===lines.length)FirstDay.finishScene(s,id)})){if(FirstDay.data(state).dialogue[id]===lines.length&&!['seller','work'].includes(id)){closeYard();if(id==='epilogo')openYard('epilogue')}else renderYard()}});return true}
 if(yardView==='trip')return renderTrip(body);if(yardView==='niva-hire'){heading(l.nivaTitle);storyParagraph(body,l.nivaHint);storyParagraph(body,l.nivaWage+' · '+storyMoney(600));if(EventFlags.has(state,'niva_contratado'))storyParagraph(body,l.nivaHired,'fight-mood');else{storyButton(body,l.nivaHire,'hire',()=>{if(storyCommit(s=>EventFlags.set(s,'niva_contratado'))){renderYard();$('yardFeedback').textContent=l.nivaHired}});storyButton(body,l.nivaLater,'later',()=>closeYard())}return true}
 if(yardView==='gate-locked'||yardView==='story-note'){heading(l.friend);storyParagraph(body,yardView==='gate-locked'?l.gateLocked:l.neutral);storyParagraph(body,storyObjective());return true}
 if(yardView==='shift'){heading(l.workTitle);storyParagraph(body,l.workHint,'shift-hint');storyButton(body,l.start,'start',()=>{closeYard();canvas.focus()});return true}
 if(yardView==='pay'){heading(l.paid);const w=d.shift;for(const [key,n] of [['salary',FirstDay.CONFIG.salary],['bonus',w.earned-FirstDay.CONFIG.salary],['total',w.earned]])storyParagraph(body,l[key]+' · '+storyMoney(n));storyParagraph(body,d.repeatJob?l.payHintAgain:l.payHint);return true}
 if(yardView==='offer'){heading(l.offer);const c=document.createElement('canvas');c.width=320;c.height=200;c.className='rooster-portrait';RouteArt.rooster(c.getContext('2d'),160,154,3);body.append(c);storyParagraph(body,l.offerHint);if(d.refusals)storyParagraph(body,l['refusal'+d.refusals]);storyParagraph(body,l.price+' · '+storyMoney(FirstDay.price(state)));storyParagraph(body,l.balance+' · '+storyMoney(state.money-FirstDay.price(state)));storyButton(body,l.buy,'buy',()=>{if(storyCommit(s=>FirstDay.buy(s,GameState.createRooster))){closeYard();$('toast').textContent=l.readyHome;$('toast').hidden=false;toastUntil=performance.now()+5000}});if(d.refusals<2)storyButton(body,l.refuse,'refuse',()=>{if(storyCommit(s=>{FirstDay.data(s).refusals=Math.min(2,FirstDay.data(s).refusals+1)}))renderYard()});return true}
 if(yardView==='rooster'){heading(l.rooster);const r=state.roosters.byId[FirstDay.CONFIG.roosterId],c=document.createElement('canvas');c.width=360;c.height=210;c.className='rooster-portrait';RouteArt.rooster(c.getContext('2d'),180,165,3);body.append(c);storyParagraph(body,l.roosterHint);const label=document.createElement('label');label.textContent=l.name;const input=document.createElement('input');input.id='roosterName';input.value=r.name;input.maxLength=40;label.append(input);body.append(label);storyButton(body,l.saveName,'name',()=>{if(storyCommit(s=>FirstDay.care(s,'name',input.value))){renderYard();$('yardFeedback').textContent=l.saved}else $('yardFeedback').textContent=l.invalidName});storyParagraph(body,l.condition+' · '+l.conditionText);if(typeof Combat!=='undefined'){const mood=Combat.currentMood(r,state.clock.day);if(mood)storyParagraph(body,LOCALES[lang].combat.mood[mood.result],'fight-mood')}storyParagraph(body,r.care.fedDay===state.clock.day?l.fed:l.hungry);storyParagraph(body,r.care.waterDay===state.clock.day?l.watered:l.thirsty);const noFood=!(state.inventory.items.feed>0||state.inventory.items.corn>0);if(noFood)storyParagraph(body,l.noFeed);storyButton(body,l.feed,'feed',()=>{if(storyCommit(s=>FirstDay.care(s,'feed')))renderYard()},noFood||r.care.fedDay===state.clock.day);storyButton(body,l.waterBird,'water',()=>{if(storyCommit(s=>FirstDay.care(s,'water')))renderYard()},r.care.waterDay===state.clock.day);if(FirstDay.data(state).phase==='complete'&&typeof LOCALES[lang].plantel!=='undefined')storyParagraph(body,LOCALES[lang].plantel.hintFromCare);return true}return false}
function storyWorkHUD(){const hud=$('workHud'),w=FirstDay.data(state)?.shift;if(!w||w.paid||state.world.room!=='depot'||FirstDay.data(state).phase!=='work'){hud.hidden=true;return}const l=storyL(),o=FirstDay.order(w.index),remaining=Math.ceil((FirstDay.CONFIG.shiftMs-w.elapsedMs)/1000);hud.hidden=false;$('workHudLabel').textContent=l.order+' #'+(w.index+1)+' · '+l['bench'+(o.bench?'B':'A')];$('workHudOrder').textContent=o.items.map(i=>l.items[i]).join(' + ');$('workHudBasket').textContent=l.basket+' · '+(w.basket.map(i=>l.items[i]).join(' + ')||'—')+' · '+l.workHudHint;$('workHudStats').textContent=l.remaining+' '+Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0')+' · '+l.score+' '+w.correct+' · '+l.errors+' '+w.errors}
function storyWorkAction(type,value){let outcome;const result=storyCommit(s=>{outcome=FirstDay.workAction(s,type,value);return outcome});const l=storyL();if(result){storyWorkHUD();if(type==='deliver'){$('toast').textContent=l[outcome];$('toast').hidden=false;toastUntil=performance.now()+2500;if(typeof yardSound==='function')yardSound(outcome==='correct'?'correct':'wrong')}}else{$('toast').textContent=type==='pick'?l.full:l.wrong;$('toast').hidden=false;toastUntil=performance.now()+2500;if(typeof yardSound==='function')yardSound('wrong')}}

function storyTick(dt){if(!activeSlot||!FirstDay.enabled(state)||document.hidden)return;const before=FirstDay.data(state).phase;FirstDay.sync(state);if(before!==FirstDay.data(state).phase){missions.sync();ui();save()}
 if(FirstDay.data(state).phase==='work'&&!document.querySelector('dialog[open]')&&!transition){if(FirstDay.tickWork(state,Math.round(dt*1000))){missions.sync();save();ui();storyWorkHUD();$('toast').textContent=storyL().paid;$('toast').hidden=false;toastUntil=performance.now()+5000;if(typeof yardSound==='function')yardSound('victory')}else storyWorkHUD()}
 if(!document.querySelector('dialog[open]')&&!transition&&state.world.room==='street'&&FirstDay.data(state).phase==='return'&&!EventFlags.has(state,'sellerCalled')&&state.player.y>=1050)storyOpenScene('seller');
}
window.addEventListener('keydown',e=>{if(e.target.matches('input,select')||!$('yardPanel').open||$('confirmAction').open||$('menu').open||$('slots').open||e.repeat)return;const k=e.key.toLowerCase();if(yardView?.startsWith('scene-')&&k==='enter'){e.preventDefault();$('yardBody').querySelector('[data-story="next"]')?.click()}});

window.addEventListener('blur',()=>{if(yardView==='shift'&&$('yardPanel').open){closeYard();menu()}});
