// Desktop saves live outside the build folder; browser mode retains localStorage.
const storage={getItem(key){return window.desktopStorage?window.desktopStorage.getItem(key):localStorage.getItem(key)},setItem(key,value){if(window.desktopStorage)window.desktopStorage.setItem(key,value);else localStorage.setItem(key,value)}};
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),art=createArt(ctx),keys=new Set(),SAVE='quintal.save.v1';
// O protagonista usa a folha animada (assets/npcs/protagonista) quando carregada; senao cai no desenho antigo.
(()=>{const old=art.person;art.person=function(x,y,step=0,npc=false,face=0){if(!npc&&typeof RouteArt!=='undefined'&&RouteArt.hasAnim('protagonista')){const dir=face===2?'up':face===1?'right':face===-1?'left':'down';if(RouteArt.drawAnim(ctx,x,y,'protagonista',dir,step>0,step/13))return}return old.apply(this,arguments)}})();
ctx.scale(2,2);
let state=GameState.create(),missions=new QuestManager(state),transition=null;
const saves=new SaveManager(storage);
// O bairro e um mapa aberto: o quintal e as ruas sao o mesmo espaco.
function roomSize(room){return room==='yard'?{w:DistrictMap.WIDTH,h:DistrictMap.HEIGHT}:{w:RouteMap.specs[room]?.width||640,h:RouteMap.specs[room]?.height||640}}
// Saves feitos na antiga sala 'street' voltam para o bairro, junto ao portao.
function relocateLegacyStreet(s){if(s?.world?.room==='street'){s.world.room='yard';s.player={...DistrictMap.gateExit}}return s}
function enterRoom(target){keys.clear();near=null;$('prompt').style.display='none';transition={target,from:state.world.room,time:0,switched:false};}
function updateTransition(dt){if(!transition)return;transition.time+=dt;if(transition.time>=.18&&!transition.switched){state.world.room=transition.target;state.player={...(state.world.room==='home'?HOUSE.spawn:RouteMap.specs[state.world.room]?RouteMap.spawn[state.world.room]:transition.from==='depot'?{...DistrictMap.depotReturn}:(()=>{const o=WORLD.getObjects(state).find(o=>o.id==='home');return {x:o.x,y:o.y+12}})())};if(FirstDay.enabled(state)&&state.world.room==='yard'&&transition.from==='depot'&&FirstDay.data(state).phase==='return'){state.clock.minutes=Math.max(state.clock.minutes,1110);state.clock.period='night'}face=state.world.room==='home'?2:0;transition.switched=true;missions.sync();ui();storyWorkHUD?.();save()}if(transition.time>=.4)transition=null;}
function drawTransition(){if(!transition)return;ctx.fillStyle='rgba(10,17,14,'+Math.max(0,Math.min(1,transition.time<.18?transition.time/.18:1-(transition.time-.18)/.22))+')';ctx.fillRect(0,0,roomSize(state.world.room).w,roomSize(state.world.room).h);}
let lang='pt-BR',moving=false,face=0,elapsed=0,near=null,storageOK=true;
let activeSlot=0;
try{lang=storage.getItem('quintal.language')||lang}catch{storageOK=false}if(!LOCALES[lang])lang='pt-BR';
function save(){try{if(activeSlot)saves.save(activeSlot,state);storage.setItem('quintal.language',lang);storageOK=true;return true}catch{storageOK=false;$('notice').textContent=LOCALES[lang].storage;return false}}
function ui(){const l=LOCALES[lang];document.documentElement.lang=lang;document.title=l.title;for(const id of ['title','eyebrow','chapter','questTitle','intro','place','farm','flavor','controls','export','importLabel'])$(id).textContent=l[id];$('language').value=lang;$('closeDialogue').textContent=l.close;
timeHUD();$('day').textContent=l.system.day+' '+state.clock.day+' · '+l.system[state.clock.period]+' · '+String(Math.floor(state.clock.minutes/60)).padStart(2,'0')+':'+String(state.clock.minutes%60).padStart(2,'0');$('money').textContent=new Intl.NumberFormat(lang,{style:'currency',currency:'BRL'}).format(state.money/100);
$('bagButton').textContent=l.yard.inventory;$('soundButton').textContent=l.yard.sounds+': '+l.yard[soundEnabled?'on':'off'];renderMissions();renderObjective();renderMenu();if(!storageOK)$('notice').textContent=l.storage;
if(typeof updatePlantelButton==='function')updatePlantelButton();if(typeof renderHotbar==='function')renderHotbar();}
function renderMissions(){const l=LOCALES[lang];$('questTitle').textContent=l.system.journal;$('intro').textContent=l.system.questHint;const lookup=key=>key.split('.').reduce((o,k)=>o?.[k],l)||key;$('routine').replaceChildren();const daily=state.agriculture.daily;for(const [key,label] of [['prepared','prepared'],['planted','planted'],['watered','watered'],['fed','fedCount'],['collected','collected'],['harvested','harvested']]){const card=document.createElement('div');card.className='routine-stat';const n=document.createElement('strong');n.textContent=String(daily[key]);const text=document.createElement('span');text.textContent=l.yard[label];card.append(n);card.append(text);$('routine').append(card)}$('tasks').replaceChildren();
for(const {definition:q,progress:p} of missions.list().filter(q=>q.progress.status!=='locked'&&!(FirstDay.enabled(state)&&q.definition.id==='yardCare'))){const section=document.createElement('section');section.className='quest-entry';const heading=document.createElement('h3');heading.textContent=lookup(q.nameKey)+' · '+l.system[p.status];section.append(heading);const description=document.createElement('p');description.textContent=lookup(q.descriptionKey);section.append(description);
for(const step of q.steps){const sp=p.steps[step.id],row=document.createElement('div');row.className='task'+(sp.complete?' done':'');row.textContent=(sp.complete?'✓  ':'○  ')+lookup(step.nameKey)+' · '+sp.progress.reduce((a,b)=>a+b,0)+'/'+step.conditions.reduce((n,c)=>n+missions.target(c),0);section.append(row)}$('tasks').append(section)}
if(state.quests.firstSteps?.status==='completed')$('intro').textContent=l.complete;
$('journalTabs').replaceChildren();for(const tab of ['today','story'])uiTab($('journalTabs'),tab,l.interface[tab],journalTab===tab,()=>{journalTab=tab;renderMissions()});
$('routine').hidden=journalTab!=='today';$('tasks').hidden=journalTab!=='story';$('intro').textContent=journalTab==='today'?l.interface.careHint:l.system.questHint;
}
function menu(){keys.clear();moving=false;renderMenu();if(!$('menu').open){$('menu').showModal();$(activeSlot?'play':'reset').focus()}save()}
$('menuButton').onclick=menu;$('play').onclick=()=>{if(activeSlot){$('menu').close();canvas.focus()}};$('language').onchange=e=>{lang=e.target.value;ui();renderMenu();save()};$('closeDialogue').onclick=()=>{$('dialogue').close();canvas.focus()};
$('reset').onclick=()=>showSlots('new');
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([GameState.encode(state)],{type:'application/json'}));let a=document.createElement('a');a.href=url;a.download='quintal-progresso.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('notice').textContent=LOCALES[lang].saved};
$('import').onchange=async e=>{const file=e.target.files[0];if(!file||!activeSlot)return;try{if(file.size>GameState.MAX_BYTES)throw Error();const imported=GameState.decode(await file.text()).state;askAction(LOCALES[lang].system.importConfirm,()=>{saves.save(activeSlot,imported);setState(imported);ui();$('notice').textContent=LOCALES[lang].loaded})}catch{$('notice').textContent=LOCALES[lang].invalid}e.target.value=''};
function currentInteraction(){return (state.world.room==='home'?HOUSE.objects:RouteMap.specs[state.world.room]?RouteMap.objects(state):[...WORLD.getObjects(state),...(state.world.objects.firstPen?[{id:'firstRooster',x:245,y:434}]:[]),...(EventFlags.has(state,'E009')?[{id:'breedingPen',x:160,y:520}]:[]),...(EventFlags.has(state,'linhagem_visto')?[{id:'lineageSign',x:205,y:250}]:[])]).reduce((best,o)=>Math.hypot(state.player.x-o.x,state.player.y-o.y)<43&&(!best||Math.hypot(state.player.x-o.x,state.player.y-o.y)<Math.hypot(state.player.x-best.x,state.player.y-best.y))?o:best,null)}
function interact(){if(!activeSlot||transition||document.querySelector('dialog[open]'))return;near=currentInteraction();if(!near)return;keys.clear();if(storyInteract(near.id))return;if(near.id==='home'||near.id==='exit'){enterRoom(near.id==='home'?'home':'yard');return;}if(near.id==='plot'){const tutorialGate=FirstDay.enabled(state)&&FirstDay.data(state).phase==='routine'&&!(EventFlags.has(state,'day1_prepare')&&EventFlags.has(state,'day1_plant')&&EventFlags.has(state,'day1_water'));if(tutorialGate){missions.setFlag('visitedGarden');save();ui();openYard('garden');return;}plotInteract(near);return;}if(near.id==='feed'){feedInteract(near);return;}if(near.id==='nest'){nestInteract(near);return;}if(['garden','coop','bed','kitchen'].includes(near.id)){if(near.id==='garden')missions.setFlag('visitedGarden');if(near.id==='coop')missions.setFlag('inspectedCoop');save();ui();openYard(near.id);return;}if(near.id==='breedingPen'){save();ui();openYard('breeding');return;}if(near.id==='lineageSign'){save();ui();openYard('lineage');return;}if(near.id==='busStop'&&typeof International!=='undefined'&&International.unlocked(state)){save();ui();openYard('international');return;}if(near.id==='emptyLot'&&typeof Construction!=='undefined'&&Construction.available(state)){save();ui();openYard('construction');return;}const l=LOCALES[lang],key=near.id.replace(/\d+$/,'');$('speaker').textContent=l.names[key]||key;$('line').textContent=l.lines[key]||'';$('dialogue').showModal();const flags={friend:'talkedToFriend',coop:'inspectedCoop',garden:'visitedGarden'};if(flags[near.id]){missions.setFlag(flags[near.id]);missions.emit({id:'inspect:'+near.id,type:near.id==='friend'?'talk':'inspect',target:near.id});if(near.id==='friend')state.npcs.friend.met=true;}save();ui()}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(e.target.matches('input,select')&&k!=='escape')return;if(['arrowup','arrowdown','arrowleft','arrowright','escape','q','i'].includes(k))e.preventDefault();if(k===' '&&!document.querySelector('dialog[open]'))e.preventDefault();if(e.repeat&&['escape','q','e','i'].includes(k))return;
if(k==='escape'){keys.clear();if($('confirmAction').open)$('confirmAction').close();else if($('slots').open)$('slots').close();else if($('yardPanel').open)closeYard();else if($('quests').open)$('quests').close();else if($('dialogue').open)$('dialogue').close();else if($('menu').open){if(activeSlot)$('menu').close()}else menu();return}
if(k==='i'){toggleInventory();return}
if(k==='q'){toggleJournal();return}
if(!activeSlot||transition||document.querySelector('dialog[open]'))return;if(k==='e'){interact();return}if(/^[1-9]$/.test(k)&&typeof hotbarSlots==='function'){const slot=hotbarSlots()[Number(k)-1];if(slot)equipHotbar(slot.id);return}keys.add(k)});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();save();if(activeSlot&&!document.querySelector('dialog[open]'))menu()});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();save();if(activeSlot&&!document.querySelector('dialog[open]'))menu()}});window.addEventListener('beforeunload',save);setInterval(save,5000);
function update(dt){moving=false;if(!activeSlot||transition||document.querySelector('dialog[open]'))return;let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dy=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));let len=Math.hypot(dx,dy);if(len){moving=true;if(dx)face=Math.sign(dx);else if(dy)face=dy<0?2:0;let speed=GameTime.speed(state,keys.has('shift'));dx=dx/len*speed*dt;dy=dy/len*speed*dt;if(!(RouteMap.specs[state.world.room]?RouteMap.blocked(state.world.room,state.player.x+dx,state.player.y):(state.world.room==='home'?HOUSE:WORLD).blocked(state.player.x+dx,state.player.y,state)))state.player.x+=dx;if(!(RouteMap.specs[state.world.room]?RouteMap.blocked(state.world.room,state.player.x,state.player.y+dy):(state.world.room==='home'?HOUSE:WORLD).blocked(state.player.x,state.player.y+dy,state)))state.player.y+=dy}if(state.world.room==='yard'&&FirstDay.enabled(state)&&!WORLD.inYard(state.player.x,state.player.y)&&!FirstDay.data(state).routeSeen){FirstDay.data(state).routeSeen=true;EventFlags.set(state,'E002');missions.sync();ui();save()}
near=currentInteraction();$('prompt').style.display=near?'block':'none';if(near)$('prompt').textContent=LOCALES[lang].interact+(near.id==='plot'&&typeof plotPromptLabel==='function'?plotPromptLabel(near):near.id==='feed'&&typeof feedPromptLabel==='function'?feedPromptLabel():near.id==='nest'&&typeof nestPromptLabel==='function'?nestPromptLabel():storyInteractionName(near.id))}
function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#182c21';ctx.fillRect(0,0,canvas.width,canvas.height);const scale=Math.max(canvas.width,canvas.height)/640;const px=state.world.room==='home'?320:state.player.x,py=state.world.room==='home'?320:state.player.y;const room=roomSize(state.world.room);const ox=Math.max(canvas.width-room.w*scale,Math.min(0,canvas.width/2-px*scale)),oy=Math.max(canvas.height-room.h*scale,Math.min(0,canvas.height/2-py*scale));ctx.setTransform(scale,0,0,scale,ox,oy);ctx.imageSmoothingEnabled=false;if(RouteMap.specs[state.world.room]){RouteArt[state.world.room](ctx,state,elapsed,art);return}if(state.world.room==='home'){HOUSE.draw(ctx,art,state.player,moving?elapsed*13:0,face,elapsed);return}DistrictArt.drawGround(ctx,state);ModularYard.drawGround(ctx,state);DistrictArt.drawAvenue(ctx,elapsed);
const friend=YardMap.resolve(state,'friend'),hens=YardMap.resolve(state,'hens');
const actors=[...ModularYard.objects(state),...DistrictArt.objects(state,elapsed,art)];
actors.push({y:friend.y,draw:()=>FirstDay.enabled(state)?RouteArt.person(ctx,friend.x,friend.y,storyNpcAtGate()):art.person(friend.x,friend.y,0,true)});if(state.world.objects.firstPen)actors.push({y:427,draw:()=>RouteArt.pen(ctx,state)});if(EventFlags.has(state,'E009'))actors.push({y:510,draw:()=>RouteArt.breedingPen(ctx,state)});if(EventFlags.has(state,'E017'))actors.push({y:184,draw:()=>RouteArt.trophy(ctx,268,184)});if(EventFlags.has(state,'linhagem_visto')&&typeof drawLineageSign==='function')actors.push({y:250,draw:()=>drawLineageSign(ctx,state,205,250)});
for(let i=0;i<3;i++){const x=hens.x+i*29+Math.sin(elapsed*.4+i*3)*9,y=hens.y+Math.cos(elapsed*.5+i)*10;actors.push({y,draw:()=>art.chicken(x,y,elapsed,i)})}
actors.push({y:state.player.y,draw:()=>art.person(state.player.x,state.player.y,moving?elapsed*13:0,false,face)});
actors.sort((a,b)=>a.y-b.y).forEach(entry=>ModularYard.drawObject(ctx,entry));
if(!EventFlags.has(state,'talkedToFriend')){art.r(friend.x-2,friend.y-60+Math.sin(elapsed*2)*2,4,10,'#ffe199');art.r(friend.x-2,friend.y-47+Math.sin(elapsed*2)*2,4,3,'#ffe199')}
ModularYard.overlay(ctx,state);if(FirstDay.enabled(state)&&FirstDay.data(state).phase==='routine'){const t=!FirstDay.data(state).intro?'friend':!EventFlags.has(state,'day1_prepare')||!EventFlags.has(state,'day1_plant')||!EventFlags.has(state,'day1_water')?'plot':'coop';const o=WORLD.getObjects(state).find(o=>o.id===t);if(o){ctx.strokeStyle='#e3c576';ctx.lineWidth=2;ctx.beginPath();ctx.arc(o.x,o.y,22+Math.sin(elapsed*3)*2,0,Math.PI*2);ctx.stroke()}}}
let last=performance.now();function frame(now){let dt=Math.min((now-last)/1000,.04);last=now;storyTick(dt);if(activeSlot&&!document.querySelector('dialog[open]')){elapsed+=dt;updateTransition(dt);update(dt);if(!transition){const tired=state.energy<=15||state.hunger>=85;if(GameTime.tick(state,dt))timeHUD();if(!tired&&(state.energy<=15||state.hunger>=85))yardFeedback(LOCALES[lang].time.tired,'error');}}else moving=false;if(performance.now()>toastUntil)$('toast').hidden=true;draw();drawTime();drawTransition();requestAnimationFrame(frame)}ui();resizeGame();menu();requestAnimationFrame(frame);

function timeHUD(){const l=LOCALES[lang];$('day').textContent=l.system.day+' '+state.clock.day+' · '+l.system[state.clock.period]+' · '+String(Math.floor(state.clock.minutes/60)).padStart(2,'0')+':'+String(state.clock.minutes%60).padStart(2,'0');$('needs').replaceChildren();for(const [id,value] of [['energy',state.energy],['hunger',state.hunger]]){const row=document.createElement('div');row.className='need-row';const label=document.createElement('span');label.textContent=l.time[id]+' '+value;const meter=document.createElement('progress');meter.max=100;meter.value=value;meter.setAttribute('aria-label',l.time[id]);row.dataset.critical=String(id==='energy'?value<=15:value>=85);row.append(label);row.append(meter);$('needs').append(row)}$('needs').title=state.energy<=15||state.hunger>=85?l.time.tired:l.time.hint;}
function drawTime(){const r=roomSize(state.world.room);ctx.fillStyle='rgba(20,25,65,'+(GameTime.darkness(state.clock)*(state.world.room==='home'?.45:1))+')';ctx.fillRect(0,0,r.w,r.h);}
