const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const noop=()=>{},elements=new Map(),handlers={},context=new Proxy({},{get:(_,key)=>key==='createLinearGradient'||key==='createRadialGradient'?()=>({addColorStop:noop}):noop,set:()=>true});
function createElement(id=''){return {id,open:false,value:'pt-BR',classList:{toggle:noop,remove:noop},dataset:{},hidden:false,style:{},textContent:'',files:[],children:[],setAttribute:noop,showModal(){this.open=true},close(){this.open=false},focus:noop,replaceChildren(){this.children=[]},append(x){this.children.push(x)},addEventListener:noop,matches:()=>false,getContext:()=>context}}
function element(id){if(!elements.has(id))elements.set(id,createElement(id));return elements.get(id)}
const mem=new Map(),scope={innerWidth:1280,innerHeight:800,devicePixelRatio:1,console,Intl,Math,JSON,Number,Set,Blob,URL,Image:function(){},performance:{now:()=>0},requestAnimationFrame:noop,setInterval:noop,setTimeout:noop,localStorage:{getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v)},document:{getElementById:element,body:{classList:{remove:noop,toggle:noop}},querySelector:()=>[...elements.values()].find(e=>e.open)||null,querySelectorAll:()=>[...elements.values()].filter(e=>e.showModal),documentElement:{},addEventListener:noop,createElement},addEventListener:(event,handler)=>{(handlers[event]??=[]).push(handler)}};scope.window=scope;vm.createContext(scope);
for(const name of ['locales','yard-locales','time-locales','combat-locales','breeding-locales','training-locales','plantel-locales','construction-locales','interior','yard-map','district-map','world','events','quests','farm','time','first-day','route-map','combat-config','combat','genetics-config','genetics','breeding','market-config','market','construction-config','construction','training-config','training','state','saves','art','visual','characters','interior-art','actor-frames','hd-art','yard-renderer','district-art','finish-art','yard-ui','combat-ui','breeding-ui','training-ui','plantel-ui','construction-ui','menus','first-day-locales','first-day-ui','route-art','game'])vm.runInContext(fs.readFileSync('public/'+name+'.js','utf8'),scope,{filename:name+'.js'});
const run=code=>vm.runInContext(code,scope);handlers.DOMContentLoaded.forEach(fn=>fn());
const key=(k)=>handlers.keydown.forEach(fn=>fn({key:k,repeat:false,target:{matches:()=>false},preventDefault:noop}));
module.exports={run,key,element,handlers,noop,scope};
