window.LOCALES={
'pt-BR':{title:'Quintal do Aperto',eyebrow:'VIDA SIMPLES. BOLETOS COMPLEXOS.',day:'Dia 1 · Manhã',chapter:'CAPÍTULO ZERO',questTitle:'Antes que o café esfrie',intro:'Um quintal, três galinhas e dinheiro contado. Todo império começa de algum jeito.',tasks:['Converse com o Toninho','Inspecione o galinheiro','Visite a horta'],place:'INTERIOR DO BRASIL',farm:'Sítio Pé de Meia',flavor:'O nome é ambicioso. O orçamento, nem tanto.',controls:'WASD / setas: andar · Shift: correr · E: interagir · Esc: menu · Q: missões. Clique no mapa para dar foco.',menuTitle:'Um começo de nada',menuText:'Explore seu primeiro quintal. Fazenda, genética e torneios chegam em próximas builds.',play:'Entrar no quintal',export:'Exportar progresso',importLabel:'Importar progresso (.json)',reset:'Recomeçar',confirm:'Apagar o progresso desta build?',close:'Continuar',interact:'E · ',saved:'Progresso exportado.',invalid:'Arquivo de progresso inválido.',loaded:'Progresso importado.',storage:'Salvamento indisponível. Use Exportar progresso.',complete:'Tudo explorado! A próxima build amplia o galinheiro.',names:{friend:'Toninho',coop:'Galinheiro',garden:'Horta',plot:'Canteiro',home:'Casa',sign:'Estrada do bairro',well:'Tambor de água',houseDoor:'Casa do bairro',shopDoor:'Loja',gym:'Academia',busStop:'Ponto de ônibus',cityGate:'Portão da avenida',emptyLot:'Terreno vazio'},lines:{friend:'Ô, vizinho! Suas galinhas estão mais organizadas que minhas contas. Depois quero te mostrar uma competição lá no bairro. Mas primeiro: conhece teu próprio quintal!',coop:'Três galinhas e uma diretoria inteira. Na próxima build você poderá cuidar delas. Por enquanto, elas fiscalizam seu serviço.',garden:'Aqui vai nascer sua horta. Hoje só nasceu uma certeza: vai dar trabalho.',home:'Seu cantinho. Tijolo aparente, telha remendada e janela de sobra de obra.',sign:'Bairro do Sossego →\nA vila fica adiante, depois dos buracos. Os terrenos com mato poderão ser comprados em futuras builds.',well:'Tambor reaproveitado. Água encanada fica para quando o dinheiro permitir.',houseDoor:'Porta fechada. Alguém baixa a cortina e some. O bairro ainda está te estudando.',shopDoor:'A loja está de porta encostada. O comércio abre em uma build futura.',gym:'Academia do bairro. Halteres enferrujados e um ventilador que só faz barulho. Fechada por enquanto.',busStop:'O ônibus para o centro passa de hora em hora. Hoje não é dia de sair do bairro.',cityGate:'Portão da avenida, trancado. Saída do bairro só quando a história permitir.',emptyLot:'Terreno baldio. Mato alto, pedra solta e uma placa velha de futuro desenvolvimento.'}},
en:{title:'Shoestring Farm',eyebrow:'SIMPLE LIVING. COMPLICATED BILLS.',day:'Day 1 · Morning',chapter:'CHAPTER ZERO',questTitle:'Before the coffee gets cold',intro:'One yard, three hens and pocket change. Every empire starts somewhere.',tasks:['Talk to Toninho','Inspect the chicken coop','Visit the garden'],place:'RURAL BRAZIL',farm:'Nest Egg Farm',flavor:'An ambitious name. A less ambitious budget.',controls:'WASD / arrows: move · Shift: run · E: interact · Esc: menu · Q: missões. Click the map to focus.',menuTitle:'Humble beginnings',menuText:'Explore your first yard. Farming, genetics and tournaments will arrive in future builds.',play:'Enter the yard',export:'Export progress',importLabel:'Import progress (.json)',reset:'Start over',confirm:'Delete progress for this build?',close:'Continue',interact:'E · ',saved:'Progress exported.',invalid:'Invalid save file.',loaded:'Progress imported.',storage:'Saving unavailable. Use Export progress.',complete:'All explored! The next build expands the coop.',names:{friend:'Toninho',coop:'Chicken coop',garden:'Garden',plot:'Plot',home:'Home',sign:'Neighborhood road',well:'Water barrel',houseDoor:'Neighbor house',shopDoor:'Shop',gym:'Gym',busStop:'Bus stop',cityGate:'Avenue gate',emptyLot:'Empty lot'},lines:{friend:'Hey, neighbor! Your hens are better organized than my bills. I want to show you a competition in the neighborhood later. First, get to know your own yard!',coop:'Three hens. An entire board of directors. You will be able to care for them in the next build. For now, they supervise.',garden:'Your future vegetable garden. So far, the only thing growing is your to-do list.',home:'Home sweet home. Bare bricks, a patched roof and a reclaimed-board shutter.',sign:'Quiet Corner →\nThe village is down this potholed road. Overgrown lots will be available to buy in future builds.',well:'A reused barrel. Running water will have to wait until we can afford it.',houseDoor:'The door stays shut. A curtain drops behind the window. The street is still sizing you up.',shopDoor:'The shop door is only pushed to. Trading opens in a future build.',gym:'The neighborhood gym. Rusty dumbbells and a fan that only makes noise. Closed for now.',busStop:'The bus downtown runs once an hour. Today is not a day for leaving the neighborhood.',cityGate:'The avenue gate is locked. You leave the neighborhood when the story says so.',emptyLot:'A vacant lot. Tall weeds, loose stones and an old sign promising development.'}}
};

Object.assign(window.LOCALES['pt-BR'].names,{exit:'Sair para o quintal',bed:'Cama remendada',kitchen:'Cozinha improvisada',table:'Mesa de caixote'});
Object.assign(window.LOCALES['pt-BR'].lines,{bed:'A cama range, mas ainda segura os sonhos. Dormir e avançar o dia chegam em outra build.',kitchen:'Fogão usado e pia apoiada numa bancada reaproveitada. Cozinhar fica para uma próxima melhoria.',table:'Um caixote promovido a mesa. O banco tem três pernas confiáveis e uma otimista.'});
Object.assign(window.LOCALES.en.names,{exit:'Go outside',bed:'Patched bed',kitchen:'Makeshift kitchen',table:'Crate table'});
Object.assign(window.LOCALES.en.lines,{bed:'The bed creaks, but it still holds your dreams. Sleeping and advancing the day come in a later build.',kitchen:'A secondhand cooker and a sink on a reclaimed counter. Cooking comes in a future update.',table:'A packing crate promoted to a table. The stool has three reliable legs and one optimistic one.'});
Object.assign(window.LOCALES['pt-BR'],{system:{
 day:'Dia',morning:'Manhã',afternoon:'Tarde',night:'Noite',active:'Em andamento',completed:'Concluída',failed:'Encerrada',locked:'Bloqueada',
 pauseTitle:'Uma pausa no quintal',startTitle:'Todo começo cabe num quintal.',pauseText:'Respire. Seu quintal espera por você.',startText:'Pouco dinheiro, muita vontade e uma história para construir.',
 play:'Continuar · Esc',loadSlots:'Carregar jogo',saveNow:'Salvar jogo',saveSlots:'Salvar em outro slot',reset:'Novo jogo',fullscreen:'Tela cheia · F11',mainMenu:'Salvar e voltar ao início',quit:'Sair do jogo',
 closeQuests:'Fechar · Q',questButton:'Missões · Q',menuButton:'☰ Esc',slotsEyebrow:'SEU QUINTAL, SUA HISTÓRIA',closeSlots:'Voltar',confirmWarning:'Esta ação não pode ser desfeita.',confirmYes:'Confirmar',confirmNo:'Cancelar',
 saveError:'Não foi possível salvar. Seu progresso anterior foi preservado.',newTitle:'Um novo começo',saveTitle:'Salvar seu quintal',loadTitle:'Escolha sua história',yard:'No quintal',home:'Dentro de casa',empty:'Terreno livre',occupied:'Meu quintal',emptyText:'Uma nova história começa aqui.',unavailable:'Save indisponível',unavailableText:'Arquivo inválido, inacessível ou de uma versão mais nova. Ele foi preservado.',
 load:'Carregar',replace:'Substituir',saveHere:'Salvar aqui',begin:'Começar',erase:'Apagar',replaceConfirm:'Substituir o slot',deleteConfirm:'Apagar o slot',savedSlot:'Jogo salvo no slot',missions:'etapas',fullscreenHint:'Use F11 para alternar a tela cheia.',importConfirm:'Substituir o progresso atual pelo arquivo importado?'
}});
Object.assign(window.LOCALES.en,{system:{
 day:'Day',morning:'Morning',afternoon:'Afternoon',night:'Night',active:'In progress',completed:'Completed',failed:'Ended',locked:'Locked',
 pauseTitle:'A moment to breathe',startTitle:'Every beginning fits in a backyard.',pauseText:'Take a breath. Your yard can wait.',startText:'Little money, big hopes and a story to build.',
 play:'Resume · Esc',loadSlots:'Load game',saveNow:'Save game',saveSlots:'Save to another slot',reset:'New game',fullscreen:'Fullscreen · F11',mainMenu:'Save and return to title',quit:'Quit game',
 closeQuests:'Close · Q',questButton:'Quests · Q',menuButton:'☰ Esc',slotsEyebrow:'YOUR YARD, YOUR STORY',closeSlots:'Back',confirmWarning:'This action cannot be undone.',confirmYes:'Confirm',confirmNo:'Cancel',
 saveError:'Could not save. Your previous progress was preserved.',newTitle:'A fresh start',saveTitle:'Save your yard',loadTitle:'Choose your story',yard:'In the yard',home:'Inside the house',empty:'Empty plot',occupied:'My yard',emptyText:'A new story begins here.',unavailable:'Save unavailable',unavailableText:'Invalid, inaccessible or newer-version save. It has been preserved.',
 load:'Load',replace:'Replace',saveHere:'Save here',begin:'Start',erase:'Delete',replaceConfirm:'Replace slot',deleteConfirm:'Delete slot',savedSlot:'Game saved in slot',missions:'steps',fullscreenHint:'Use F11 to toggle fullscreen.',importConfirm:'Replace current progress with the imported file?'
}});
window.LOCALES.en.controls='WASD / arrows: move · Shift: run · E: interact · Esc: menu · Q: quests. Click the map to focus.';

Object.assign(window.LOCALES['pt-BR'].system,{journal:'Caderno de missões',questHint:'Cada pequeno passo conta. Seu progresso é salvo com o quintal.'});
Object.assign(window.LOCALES.en.system,{journal:'Quest journal',questHint:'Every small step counts. Your progress is saved with your yard.'});
