window.LOCALES['pt-BR'].yard={
 title:'Quintal vivo',garden:'Horta de sobrevivência',coop:'Galinheiro remendado',bed:'Cama remendada',inventory:'Sacola · I',close:'Voltar · Esc',plot:'Canteiro',bare:'Terra por preparar',tilled:'Pronto para plantar',seed:'Semente plantada',growing:'Crescendo',ready:'Pronto para colher',wet:'Regado hoje',dry:'Solo seco',growth:'noites regadas',
 prepare:'Arar',plant:'Plantar',plantHint:'Equipe uma semente para plantar',water:'Regar',harvest:'Colher',feed:'Servir ração',cornFeed:'Servir milho',collect:'Recolher ovos',sleep:'Dormir até amanhã',sleepConfirm:'Encerrar o dia e dormir?',sleepHint:'O dia só passa ao dormir. Plantas regadas crescem uma etapa. Cada galinha alimentada põe um ovo. O que não recebeu cuidado apenas espera.',sleepWarning:'Confira a horta e as galinhas antes de encerrar o dia.',
 hotbar:{hoe:'Enxada',wateringcan:'Regador',radishSeed:'Sementes de rabanete',cornSeed:'Sementes de milho'},feedHint:'Equipe ração ou milho para servir',
 gardenHint:'Rabanete: 2 noites regadas → 3 unidades. Milho: 3 noites regadas → 6 unidades. Cada colheita devolve 2 sementes. Sem rega, a planta espera; ela não morre.',coopHint:'Cada galinha consome 1 porção por dia e põe 1 ovo ao dormir se foi alimentada. Cada ninho cabe 3 ovos. Sem alimento, não há ovo novo. O milho da horta também serve de comida.',fed:'Alimentada hoje',hungry:'Ainda não comeu hoje',hen:'Galinha',eggs:'ovos no ninho',bagHint:'Sementes e ração vieram na mudança. Plante milho para manter a alimentação das galinhas. Água da lata é ilimitada nesta etapa.',
 items:{radishSeed:'Sementes de rabanete',cornSeed:'Sementes de milho',feed:'Ração',corn:'Milho',radish:'Rabanetes',egg:'Ovos'},
 feedback:{prepare:'Terra preparada. A enxada ainda dá conta!',plant:'Semente plantada. Agora é regar e esperar.',water:'Regado! O solo ficou úmido.',harvest:'Colheita na sacola: +{amount} {crop} e +2 sementes.',feed:'Comida servida para {amount} galinhas.',collect:'+{amount} ovos na sacola.',alreadyPrepared:'Este canteiro já está preparado.',prepareFirst:'Prepare o canteiro primeiro.',occupied:'Já existe uma planta aqui.',noSeeds:'Você não tem essa semente.',alreadyWatered:'Este canteiro já foi regado hoje.',readyWater:'Já está maduro. Pode colher!',notReady:'Ainda não está pronto para colher.',alreadyFed:'As três já comeram hoje.',noFeed:'É preciso 1 porção por galinha ainda sem comida.',noEggs:'Os ninhos estão vazios. Alimente e durma para produzir mais.',invalid:'Essa ação não está disponível.',sleep:'Bom dia! O quintal acordou com você.',needHoe:'Equipe a enxada (barra de itens) para arar aqui.',needSeed:'Equipe uma semente (barra de itens) para plantar aqui.',needWateringCan:'Equipe o regador (barra de itens) para regar aqui.',needFeed:'Equipe ração ou milho (barra de itens) para servir aqui.'},
 morning:'Uma nova manhã',summary:'Dia {day}: {grew} canteiros cresceram; {ready} ficaram prontos. +{eggs} ovos nos ninhos. {hungry} galinhas não produziram por falta de comida; {full} estavam com ninho cheio.',routine:'Cuidados de hoje',prepared:'canteiros preparados',planted:'plantios',watered:'regas',fedCount:'galinhas alimentadas',collected:'ovos recolhidos',harvested:'produtos colhidos',
 questName:'Primeiros cuidados',questDescription:'Com ferramentas gastas e alguns pacotinhos, faça a primeira rotina do quintal. Conclua no seu ritmo, ao longo dos dias.',prepareTask:'Prepare um canteiro',plantTask:'Plante uma semente',waterTask:'Regue um canteiro',feedTask:'Alimente as galinhas',collectTask:'Recolha ovos',harvestTask:'Faça sua primeira colheita',road:'Saída para a estrada',roadHint:'Um portão de madeira velha, amarrado com arame. A saída está aqui à direita, mas a estrada ainda não está acessível.',sounds:'Sons',on:'ligados',off:'desligados'
};
window.LOCALES.en.yard={
 title:'Living yard',garden:'Survival garden',coop:'Patched chicken coop',bed:'Patched bed',inventory:'Bag · I',close:'Back · Esc',plot:'Plot',bare:'Untilled soil',tilled:'Ready to plant',seed:'Seed planted',growing:'Growing',ready:'Ready to harvest',wet:'Watered today',dry:'Dry soil',growth:'watered nights',
 prepare:'Till',plant:'Plant',plantHint:'Equip a seed to plant',water:'Water',harvest:'Harvest',feed:'Serve feed',cornFeed:'Serve corn',collect:'Collect eggs',sleep:'Sleep until tomorrow',sleepConfirm:'End the day and sleep?',sleepHint:'Days only pass when you sleep. Watered plants grow one stage. Each fed hen lays one egg. Anything uncared for simply waits.',sleepWarning:'Check the garden and hens before ending the day.',
 hotbar:{hoe:'Hoe',wateringcan:'Watering can',radishSeed:'Radish seeds',cornSeed:'Corn seeds'},feedHint:'Equip feed or corn to serve',
 gardenHint:'Radish: 2 watered nights → 3 units. Corn: 3 watered nights → 6 units. Every harvest returns 2 seeds. Without water, plants wait; they do not die.',coopHint:'Each hen eats 1 portion per day and lays 1 egg overnight if fed. Each nest holds 3 eggs. No food means no new egg. Homegrown corn also works as feed.',fed:'Fed today',hungry:'Not fed today',hen:'Hen',eggs:'eggs in the nest',bagHint:'Seeds and feed came with the move. Grow corn to keep the hens fed. Your tin watering can has unlimited water in this build.',
 items:{radishSeed:'Radish seeds',cornSeed:'Corn seeds',feed:'Feed',corn:'Corn',radish:'Radishes',egg:'Eggs'},
 feedback:{prepare:'Soil tilled. The old hoe still works!',plant:'Seed planted. Time to water and wait.',water:'Watered! The soil is damp now.',harvest:'Into the bag: +{amount} {crop} and +2 seeds.',feed:'Food served to {amount} hens.',collect:'+{amount} eggs in your bag.',alreadyPrepared:'This plot is already tilled.',prepareFirst:'Till the plot first.',occupied:'There is already a plant here.',noSeeds:'You do not have that seed.',alreadyWatered:'This plot is already watered today.',readyWater:'It is ripe. Time to harvest!',notReady:'Not ready to harvest yet.',alreadyFed:'All three have eaten today.',noFeed:'You need 1 portion for each unfed hen.',noEggs:'The nests are empty. Feed the hens and sleep for more eggs.',invalid:'That action is unavailable.',sleep:'Good morning! Your yard is awake.',needHoe:'Equip the hoe (item bar) to till here.',needSeed:'Equip a seed (item bar) to plant here.',needWateringCan:'Equip the watering can (item bar) to water here.',needFeed:'Equip feed or corn (item bar) to serve here.'},
 morning:'A new morning',summary:'Day {day}: {grew} plots grew; {ready} became ripe. +{eggs} eggs in the nests. {hungry} hens lacked food; {full} had full nests.',routine:'Today’s care',prepared:'plots tilled',planted:'seeds planted',watered:'plots watered',fedCount:'hens fed',collected:'eggs collected',harvested:'items harvested',
 questName:'First care',questDescription:'With worn tools and a few seed packets, start your first yard routine. Complete it at your own pace over several days.',prepareTask:'Till a plot',plantTask:'Plant a seed',waterTask:'Water a plot',feedTask:'Feed the hens',collectTask:'Collect eggs',harvestTask:'Harvest your first crop',road:'Road exit',roadHint:'An old wooden gate held together with wire. The exit is here on the right, but the road is not accessible yet.',sounds:'Sounds',on:'on',off:'off'
};
for(const [lang,l] of Object.entries(window.LOCALES)){
 l.names.sign=l.yard.road;l.lines.sign=l.yard.roadHint;
 l.lines.garden=l.yard.gardenHint;l.lines.coop=l.yard.coopHint;l.lines.bed=l.yard.sleepHint;
 l.complete=lang==='en'?'You know your yard. Time to care for it!':'Você já conhece o quintal. Agora é cuidar dele!';
 l.controls+=lang==='en'?' I: bag. Sleep in bed to advance the day.':' I: sacola. Durma na cama para avançar o dia.';
}
window.LOCALES['pt-BR'].interface={
 today:'Hoje',story:'História',objective:'Próximo passo',showObjective:'Mostrar objetivo',hideObjective:'Recolher objetivo',freeDay:'Cuidados em dia. Explore no seu ritmo.',
 all:'Tudo',food:'Alimentos',agriculture:'Agricultura',husbandry:'Criação',other:'Outros',quantity:'Na sacola',uses:'Como usar',empty:'Nada por aqui ainda.',emptyHint:'Os produtos colhidos e os ovos recolhidos aparecem na sua sacola.',details:'Detalhes do item',
 full:'Você está sem fome.',noItem:'Não há unidades disponíveis.',mealUsed:'A refeição de hoje já foi servida.',unavailable:'Este save não pode ser carregado. Você pode apagá-lo ou substituí-lo após confirmar.',
 careHint:'Seu registro de cuidados recomeça a cada dia. As missões guardam o progresso.',
 itemDescriptions:{radishSeed:'Um pacotinho simples para começar a horta.',cornSeed:'Sementes para comida e para as galinhas.',feed:'Porções de ração guardadas para o galinheiro.',corn:'Milho colhido no próprio quintal.',radish:'Rabanetes frescos da sua horta.',egg:'Ovos das suas galinhas de produção.'},
 itemUses:{radishSeed:'Plante em terra preparada e regue. Colha após 2 noites regadas.',cornSeed:'Plante em terra preparada e regue. Colha após 3 noites regadas.',feed:'Sirva no galinheiro: 1 porção por galinha ainda sem comida.',corn:'Coma pela sacola ou sirva às galinhas no galinheiro.',radish:'Coma pela sacola para recuperar energia e aliviar a fome.',egg:'Coma pela sacola para recuperar energia e aliviar a fome.'},
 eatEffect:'−{hunger} fome · +3 energia · 5 min',genericItem:'Item guardado na sacola.',genericUse:'Sem ação disponível nesta etapa.',
 sellHint:'Preço de venda: {preco} por unidade.',sellAll:'Vender tudo ({valor})',sellDone:'Vendido por {valor}.'
};
window.LOCALES.en.interface={
 today:'Today',story:'Story',objective:'Next step',showObjective:'Show objective',hideObjective:'Collapse objective',freeDay:'Care is done. Explore at your own pace.',
 all:'All',food:'Food',agriculture:'Gardening',husbandry:'Husbandry',other:'Other',quantity:'In your bag',uses:'How to use',empty:'Nothing here yet.',emptyHint:'Harvested produce and collected eggs appear in your bag.',details:'Item details',
 full:'You are not hungry.',noItem:'No units available.',mealUsed:'Today’s meal has already been served.',unavailable:'This save cannot be loaded. You can delete or replace it after confirmation.',
 careHint:'Your care record starts fresh each day. Quests keep their progress.',
 itemDescriptions:{radishSeed:'A simple packet to get your garden started.',cornSeed:'Seeds for your meals and your hens.',feed:'Feed portions kept for the chicken coop.',corn:'Corn harvested in your own yard.',radish:'Fresh radishes from your garden.',egg:'Eggs from your laying hens.'},
 itemUses:{radishSeed:'Plant in tilled soil and water. Harvest after 2 watered nights.',cornSeed:'Plant in tilled soil and water. Harvest after 3 watered nights.',feed:'Serve at the coop: 1 portion per hen that has not eaten.',corn:'Eat from your bag or serve to the hens at the coop.',radish:'Eat from your bag to restore energy and ease hunger.',egg:'Eat from your bag to restore energy and ease hunger.'},
 eatEffect:'−{hunger} hunger · +3 energy · 5 min',genericItem:'An item kept in your bag.',genericUse:'No action available at this stage.',
 sellHint:'Sale price: {preco} per unit.',sellAll:'Sell all ({valor})',sellDone:'Sold for {valor}.'
};
